### ISSUE TITLE
UI改善: 設定変更、ファイル保存機能を実装する

### ISSUE THREAD

**Issue by u-masao** [u-masao/embed-text-recommender#35]

**Comment by u-masao** [comment]
とりあえずテキストエディタで ui.yaml を修正してリロードすれば動くようになったので、後回しでもOK。

**Comment by u-masao** [comment]
設定ファイルをフラットな構造にしているが、もうちょっと構造化を勧めても良さそう。

```yaml
ui:
  global:
    gradio_share: False
    defaults:
      positive_query: エンジニア 転職
      negative_query: 旅行 カメラ
      like_ids: 1234 5678
      dislike_ids: 4321 8765
      top_n: 10
  backend:
    {ここから先はリストにして、内部に設定のDictをもたせる}
```

ユーザーは、プリセットから backend を選択する。
